import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Separator } from "@/components/ui/separator";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex min-h-screen w-full flex-col items-center dark:bg-black">
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <NavBar />
              <Separator />
              <main className="flex w-full flex-grow items-center justify-center dark:bg-neutral-950">
                {children}
                <Toaster richColors />
              </main>
            </ThemeProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
